<?php
require_once "db.php";

// Create table
$conn->query("CREATE TABLE IF NOT EXISTS requirements_list (
    id INT AUTO_INCREMENT PRIMARY KEY,
    requirement_name VARCHAR(255) NOT NULL UNIQUE
)");

// Existing requirements
$requirements = [
    "1.1 Courses offered",
    "1.2 Availability of Time Tables and Academic Calendar",
    "1.3 Faculty Information",
    "1.4 Non-teaching Faculty Information",
    "1.5 Laboratory-wise Facilities",
    "1.6 Computing facilities",
    "1.7 Updated Stock Registers",
    "1.8 Adoption of safety measures",
    "1.9 Course wise & Year wise Students strength",
    "1.10 Departmental Governance (PAC / DAB / Course Coordinators)",
    "2.1 Vision and Mission of Institute",
    "2.2 Vision and Mission of Department",
    "2.3 PO, PEO, PSO Mapping",
    "2.4 UG/PG Syllabus Evidence",
    "2.5 Curriculum Revision Evidence",
    "2.6 Add-on Courses",
    "2.7 Human Values / Ethics / IKS Courses",
    "2.8 Implementation of Departmental Annual Plans",
    "2.9 Academic Calendar Adherence",
    "2.10 Department Activity Register",
    "2.11 Syllabus Coverage Evidence",
    "2.12 Attendance Registers",
    "2.13 Curriculum Feedback",
    "3.1 Course File Records",
    "3.2 Examination Records",
    "3.3 Quality of Question Papers",
    "3.4 Result Analysis (Subject-wise)",
    "3.5 Result Analysis (Faculty-wise)",
    "3.6 Term Work Records",
    "3.7 Faculty Feedback Reports",
    "3.8 Co-curricular Activity Records",
    "3.9 MOOC/NPTEL Records",
    "3.10 CO-PO Attainments",
    "3.11 Indirect Attainments",
    "3.12 Course Exit Surveys",
    "3.13 Innovative Teaching Methods",
    "3.14 Student Projects & Outcomes",
    "4.1 Research Centre Approvals",
    "4.2 Research Guides",
    "4.3 PG Guides",
    "4.4 Research Projects",
    "4.5 Research Papers",
    "4.6 Conference Publications",
    "4.7 Patents & Copyrights",
    "4.8 Consultancy Details",
    "4.9 e-content & Web Resources",
    "4.10 Working Models",
    "4.11 Faculty Appraisal Reports",
    "4.12 MoUs & Activities",
    "5.1 Professional Club Activities",
    "5.2 NSS Activities",
    "5.3 NCC Activities",
    "5.4 IIC Activities",
    "5.5 IEDC Activities",
    "5.6 Other Clubs",
    "6.1 Library Information Centre",
    "6.2 Department Library",
    "6.3 Book Circulation Records",
    "6.4 Previous Question Papers",
    "6.5 Model Answers",
    "6.6 Visitor Records",
    "6.7 Online Learning Resources",
    "7.1 Dean/Faculty Incharge Details",
    "7.2 Sports Activities",
    "7.3 Sports Achievements",
    "7.4 Cultural Programs",
    "7.5 Co/Extra-Curricular Marks",
    "7.6 Placement & Internship",
    "7.7 Training & Workshops",
    "7.8 Career Guidance",
    "7.9 Career Guidance Activities",
    "7.10 Alumni Activities",
    "7.11 Grievance / Anti Ragging / ICC",
    "7.12 Student Mentoring",
    "8.1 Drinking Water Maintenance",
    "8.2 Sanitation Maintenance",
    "8.3 Electricity & Backup Support",
    "8.4 Common Rooms",
    "8.5 Campus Greenery & Cleanliness",
    "8.6 Health Care Facilities",
    "9.1 Committee Minutes (BOS/PAC/DAB/IQAC)",
    "9.2 Stakeholders Feedback",
    "9.3 Staff Meeting Register",
    "9.4 Previous Audit Action Report",
    "10.1 LCD Projectors",
    "10.2 Teaching Aids",
    "10.3 Internet Centre",
    "10.4 Computer Labs",
    "11.1 Best Practices",
    "A1 Overall Impression",
    "A2 Areas of Improvement",
];

$stmt = $conn->prepare("INSERT IGNORE INTO requirements_list (requirement_name) VALUES (?)");
foreach($requirements as $req){
    $stmt->bind_param("s", $req);
    $stmt->execute();
}

echo "Requirements migrated successfully!";
?>
